### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by genment**
Remove useless files and clean up .csproj

### CODE REVIEW

**Comment by lastbattle** [comment]
spine-runtimes-2.1.25 has to be there, as it is the version that MapleStory uses relative to the latest version in the main branch.
https://github.com/EsotericSoftware/spine-runtimes

For more information about **spine**: 
https://orangemushroom.net/2015/06/17/developers-note-maplestory-reboot-update-introduction-2-and-3/
https://www.youtube.com/watch?v=eylrYIWlrmg
https://github.com/lastbattle/Harepacker-resurrected/releases/tag/4.0.1

**Comment by genment** [comment]
There is a duplicate copy of the spine-runtime. I removed the one that was unused.

**Comment by lastbattle** [comment]
Overlooked, merged. 😄

**Comment by genment** [comment]
Just curious, is there a specific reason you're sticking with this old version 2.1.25?

**Comment by lastbattle** [comment]
I've tried the latest, the file structures are slightly different. 
2.1.25 is the only one that works, that Nexon uses.

**Pull request merged**
